### ISSUE TITLE
Update for Big Sur

### ISSUE THREAD

**Issue by svoop** [svoop/autotest-fsevent#12]
@bvicenzo wrote:

>Hi!
>Is it possible to add support to MacOS Big Sur?
>I'm getting this error on gem installing.
>
><img width="633" alt="Captura de Tela 2021-01-27 às 18 50 30" src="https://user-images.githubusercontent.com/173159/106058940-b4efa380-60d0-11eb-8083-b205c1005c03.png">

**Comment by svoop** [comment]
@bvicenzo Sure thing. Unfortunately, my hardware is not ready for Big Sur, so I can't test it yet. Would you have a minute this afternoon to try before I cut a new release?

**Comment by svoop** [comment]
@bvicenzo Could you please try to install the gem from Master and confirm it compiles and works on Big Sur?

```
gem autotest-fsevent, github: 'svoop/autotest-fsevent', group: :development
```

**Comment by bvicenzo** [comment]
Hi!
It seems that it's been worked!

<img width="1116" alt="Captura de Tela 2021-01-28 às 20 32 29" src="https://user-images.githubusercontent.com/173159/106211793-1171c200-61a8-11eb-804b-34ca082e39b2.png">

Just to give you more context, I'm trying to configure a development environment for the gem [docusign-ruby-client](https://github.com/docusign/docusign-ruby-client), which depends on yours...

**Comment by svoop** [comment]
@bvicenzo Great, thanks for trying! I'll cut a release when I'm back at the office this afternoon.

**Comment by svoop** [comment]
@bvicenzo Released, thanks for the heads-up!
