### ISSUE TITLE
cannot load such file -- autotest upon require

### ISSUE THREAD

**Issue by mensfeld** [svoop/autotest-fsevent#13]
My name is Maciej Mensfeld and I run a research security project called https://diffend.io.

While that's not a security issue, wanted to bring to your attention, that upon requiring of this gem (diffend does that to run a sandbox for security assessment of gems based on their behaviors), it fails with:

<pre>
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- autotest-fsevent (LoadError)
	9: from -e:1:in `<main>'
	8: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	7: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	6: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	5: from /home/app/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/autotest-fsevent-0.2.18/lib/autotest-fsevent.rb:4:in `<top (required)>'
	4: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /home/app/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/autotest-fsevent-0.2.18/lib/autotest/fsevent.rb:2:in `<top (required)>'
	1: from /home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/app/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- autotest (LoadError)

</pre>

which (probably) indicates, that XYZ is not present upon loading.

repro:

Gemfile

<pre><code class="ruby">
source 'https://rubygems.org'

gem 'autotest-fsevent'
</code></pre>

steps:

1. bundle install
2. bundle exec ruby -e 'require "autotest-fsevent"'

**Comment by svoop** [comment]
You can't `require autotest-fsevent`, it's `require autotest/fsevent` as mentioned in the README. 

Furthermore, this is a plugin for autotest, so it cannot be required standalone. You have to load a test suite runner and require this plugin in your `~/.autotest`. There's no hard dependency in the gemspec since there are different test suite runners to chose from.

**Comment by mensfeld** [comment]
Thank you for the clarification.
